#!/usr/bin/env bash

ATLAS_HOME=${ATLAS_HOME:-"/opt/atlas"}

STORAGE_BACKEND_CONF="atlas.graph.storage.backend"
HBASE_STORAGE_LOCAL_CONF_ENTRY="atlas.graph.storage.hostname"
SOLR_INDEX_CONF_ENTRY="atlas.graph.index.search.backend"
SOLR_INDEX_MODE_CONF_ENTRY="atlas.graph.index.search.solr.mode"
SOLR_INDEX_LOCAL_STANDALONE_CONF_ENTRY="atlas.graph.index.search.solr.http-urls"
SOLR_INDEX_LOCAL_CLOUD_CONF_ENTRY="atlas.graph.index.search.solr.zookeeper-url"
SOLR_INDEX_ZK_URL="atlas.graph.index.search.solr.zookeeper-url"
ATLAS_MAIN_CLASS="org.apache.atlas.Atlas"

DEFAULT_JVM_HEAP_OPTS="-Xmx1024m"
DEFAULT_JVM_OPTS="-Dlog4j.configuration=atlas-log4j.xml -Djava.net.preferIPv4Stack=true -server"
DEFAULT_HBASE_CONF_DIR="${ATLAS_HOME}/conf/hbase"

ATLAS_CONF_DIR=${ATLAS_CONF_DIR:-"${ATLAS_HOME}/conf"}
ATLAS_CONF_FILE=${ATLAS_CONF_FILE:-"atlas-application.properties"}
ATLAS_LOG_DIR=${ATLAS_LOG_DIR:-"${ATLAS_HOME}/logs"}
ATLAS_LOG_FILE=${ATLAS_LOG_FILE:-"application.log"}
ATLAS_SERVER_HEAP=${ATLAS_SERVER_HEAP:-$DEFAULT_JVM_HEAP_OPTS}
ATLAS_OPTS=${ATLAS_OPTS:-$DEFAULT_JVM_OPTS}
ATLAS_CLASSPATH="${ATLAS_HOME}/conf:${ATLAS_HOME}/server/webapp/atlas/WEB-INF/classes:${ATLAS_HOME}/server/webapp/atlas/WEB-INF/lib/*:${ATLAS_HOME}/libext/*"
HBASE_CONF_DIR=${HBASE_CONF_DIR:-$DEFAULT_HBASE_CONF_DIR}
ATLAS_CONF_OPTS="-Datlas.log.dir=$ATLAS_LOG_DIR -Datlas.log.file=$ATLAS_LOG_FILE -Datlas.home=$ATLAS_HOME -Datlas.conf=${ATLAS_HOME}/conf"
ATLAS_EXPANDED_WEBAPP_DIR=${ATLAS_EXPANDED_WEBAPP_DIR:-"${ATLAS_HOME}/server/webapp"}
ATLAS_APP_METADATA_DIR=${ATLAS_APP_METADATA_DIR:-"${ATLAS_EXPANDED_WEBAPP_DIR}/atlas"}

MANAGE_LOCAL_HBASE=$(echo "${MANAGE_LOCAL_HBASE:-"False"}" | tr '[:upper:]' '[:lower:]')
MANAGE_EMBEDDED_CASSANDRA=$(echo "${MANAGE_EMBEDDED_CASSANDRA:-"False"}" | tr '[:upper:]' '[:lower:]')
MANAGE_LOCAL_SOLR=$(echo "${MANAGE_LOCAL_SOLR:-"False"}" | tr '[:upper:]' '[:lower:]')
MANAGE_LOCAL_ELASTICSEARCH=$(echo "${MANAGE_LOCAL_ELASTICSEARCH:-"False"}" | tr '[:upper:]' '[:lower:]')

function get_configuration_value {
  local __resultvar=$1
  local configuration_file=$2
  local configuration_key=$3
  eval $__resultvar="'$(grep ^${configuration_key}= "${configuration_file}" | sed s/${configuration_key}=//)'"
}

function is_hbase {
  local configuration_file=$1
  get_configuration_value "storage_backend" "$configuration_file" "$STORAGE_BACKEND_CONF"
  if [[ "$STORAGE_BACKEND" == "hbase" || "$STORAGE_BACKEND" == "hbase2" || "$STORAGE_BACKEND" == "" ]]; then
    return 1
  fi
  return 0
}

function is_hbase_local {
  local configuration_file=$1
  if [[ "$MANAGE_LOCAL_HBASE" == "true" ]]; then
    get_configuration_value "hbase_storage_local" "$configuration_file" "$HBASE_STORAGE_LOCAL_CONF_ENTRY"
    if  is_hbase "$configuration_file" && [[ -z "$hbase_storage_local" ]]; then
      return 1
    fi
  fi
  return 0
}

function is_cassandra_local {
  local manage_embedded_cassandra=${MANAGE_EMBEDDED_CASSANDRA}
  if [[ "$manage_embedded_cassandra" == "true" ]]; then
    return 1
  fi
  return 0
}

function is_solr_local {
  local configuration_file=$1
  if [[ "$MANAGE_LOCAL_SOLR" == "true" ]]; then
    if is_solr_local_cloud_mode "$configuration_file" || is_solr_local_standalone_mode "$configuration_file"; then
      return 1
    fi
  fi
  return 0
}

function is_solr_local_cloud_mode {
  local configuration_file=$1
  get_configuration_value "solr_index_mode" "$configuration_file" "$SOLR_INDEX_CONF_ENTRY"
  get_configuration_value "solr_index_local_cloud" "$configuration_file" "$SOLR_INDEX_LOCAL_CLOUD_CONF_ENTRY"
  if [[ "$solr_index_mode" == "cloud" ]] && [[ -z "$solr_index_local_cloud" ]]; then
    return 1
  fi
  return 0
}

function is_solr_local_standalone_mode {
  local configuration_file=$1
  get_configuration_value "solr_index_mode" "$configuration_file" "$SOLR_INDEX_CONF_ENTRY"
  get_configuration_value "solr_index_local_standalone" "$configuration_file" "$SOLR_INDEX_LOCAL_STANDALONE_CONF_ENTRY"
  if [[ "$solr_index_mode" == "http" ]] && [[ -z "$solr_index_local_standalone" ]]; then
    return 1
  fi
  return 0
}

function is_elasticsearch_local {
  if [[ "$MANAGE_LOCAL_ELASTICSEARCH" == "true" ]]; then
    return 1
  fi
  return 0
}

if is_hbase "${ATLAS_CONF_DIR}/${ATLAS_CONF_FILE}"; then
    if [[ -f "${HBASE_CONF_DIR}/hbase-site.xml" ]]; then
        ATLAS_CLASSPATH="${ATLAS_CLASSPATH}:${HBASE_CONF_DIR}"
    else
        echo "Could not find hbase-site.xml in ${HBASE_CONF_DIR}. Please set env var HBASE_CONF_DIR to the hbase client conf dir"
        exit 1
    fi
fi

# Which jar to use
if [ -z "$JAVA_HOME" ]; then
  JAR="jar"
else
  JAR="$JAVA_HOME/bin/jar"
fi

# Which java to use
if [ -z "$JAVA_HOME" ]; then
  JAVA="java"
else
  JAVA="$JAVA_HOME/bin/java"
fi

if [[ ! -d "${ATLAS_APP_METADATA_DIR}/WEB-INF" ]]; then
  mkdir -p "${ATLAS_APP_METADATA_DIR}/WEB-INF"
  pushd "${ATLAS_APP_METADATA_DIR}" || exit
  "$JAR" -xf "${ATLAS_EXPANDED_WEBAPP_DIR}/atlas.war"
  popd || exit
fi

"$JAVA" $ATLAS_CONF_OPTS $ATLAS_SERVER_HEAP $ATLAS_OPTS -classpath "$ATLAS_CLASSPATH" "$ATLAS_MAIN_CLASS" -app "${ATLAS_HOME}/server/webapp/atlas"