#!/usr/bin/env bash

DEFAULT_JVM_HEAP_OPTS="-Xmx1024m"
DEFAULT_JVM_OPTS="-Dlog4j.configuration=atlas-log4j.xml -Djava.net.preferIPv4Stack=true -server"
DEFAULT_HBASE_CONF_DIR="${ATLAS_HOME}/conf/hbase"

STORAGE_BACKEND_CONF="atlas.graph.storage.backend"
ATLAS_MAIN_CLASS="org.apache.atlas.Atlas"

ATLAS_HOME=${ATLAS_HOME:-"/opt/atlas"}
ATLAS_CONF_DIR=${ATLAS_CONF_DIR:-"${ATLAS_HOME}/conf"}
ATLAS_CONF_FILE=${ATLAS_CONF_FILE:-"atlas-application.properties"}
ATLAS_LOG_DIR=${ATLAS_LOG_DIR:-"${ATLAS_HOME}/logs"}
ATLAS_LOG_FILE=${ATLAS_LOG_FILE:-"application.log"}
ATLAS_SERVER_HEAP=${ATLAS_SERVER_HEAP:-$DEFAULT_JVM_HEAP_OPTS}
ATLAS_OPTS=${ATLAS_OPTS:-$DEFAULT_JVM_OPTS}
ATLAS_CLASSPATH="${ATLAS_HOME}/conf:${ATLAS_HOME}/server/webapp/atlas/WEB-INF/classes:${ATLAS_HOME}/server/webapp/atlas/WEB-INF/lib/*:${ATLAS_HOME}/libext/*"
HBASE_CONF_DIR=${HBASE_CONF_DIR:-$DEFAULT_HBASE_CONF_DIR}
ATLAS_CONF_OPTS="-Datlas.log.dir=$ATLAS_LOG_DIR -Datlas.log.file=$ATLAS_LOG_FILE -Datlas.home=$ATLAS_HOME -Datlas.conf=${ATLAS_HOME}/conf"
ATLAS_EXPANDED_WEBAPP_DIR=${ATLAS_EXPANDED_WEBAPP_DIR:-"${ATLAS_HOME}/server/webapp"}
ATLAS_APP_METADATA_DIR=${ATLAS_APP_METADATA_DIR:-"${ATLAS_EXPANDED_WEBAPP_DIR}/atlas"}

STORAGE_BACKEND=$(grep ^${STORAGE_BACKEND_CONF}= "${ATLAS_CONF_DIR}/${ATLAS_CONF_FILE}" | sed s/${STORAGE_BACKEND_CONF}=//)
if [[ "$STORAGE_BACKEND" == "hbase" || "$STORAGE_BACKEND" == "hbase2" || "$STORAGE_BACKEND" == "" ]]; then
    if [[ -f "${HBASE_CONF_DIR}/hbase-site.xml" ]]; then
        ATLAS_CLASSPATH="${ATLAS_CLASSPATH}:${HBASE_CONF_DIR}"
    else
        echo "Could not find hbase-site.xml in ${HBASE_CONF_DIR}. Please set env var HBASE_CONF_DIR to the hbase client conf dir"
        exit 1
    fi
fi

# Which jar to use
if [ -z "$JAVA_HOME" ]; then
  JAR="jar"
else
  JAR="$JAVA_HOME/bin/jar"
fi

# Which java to use
if [ -z "$JAVA_HOME" ]; then
  JAVA="java"
else
  JAVA="$JAVA_HOME/bin/java"
fi

if [[ ! -d "${ATLAS_APP_METADATA_DIR}/WEB-INF" ]]; then
  mkdir -p "${ATLAS_APP_METADATA_DIR}/WEB-INF"
  pushd "${ATLAS_APP_METADATA_DIR}" || exit
  "$JAR" -xf "${ATLAS_EXPANDED_WEBAPP_DIR}/atlas.war"
  popd || exit
fi

"$JAVA" $ATLAS_CONF_OPTS $ATLAS_SERVER_HEAP $ATLAS_OPTS -classpath "$ATLAS_CLASSPATH" "$ATLAS_MAIN_CLASS" -app "${ATLAS_HOME}/server/webapp/atlas"